print("-----------------------------------------")
print("quito problema 2025 :)")
print("-----------------------------------------")
n1 = int(input("Ingrese el primer numero: "))
print("-----------------------------------------")
n2 = int(input("Ingrese el segundo numero: "))
print("-----------------------------------------")
n3 = int(input("Ingrese el tercer numero: "))
print("-----------------------------------------")
n4 = int(input("Ingrese el cuarto numero: "))
print("-----------------------------------------")
result = (n1 * n2) - (n3 * n4)
print(f"El resultado de (({n1} * {n2}) - ({n3} * {n4})) es: {result}")
print("-----------------------------------------")